name: Docker

on: [push, pull_request]
# on:
#   release:
#     types: [created]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=0.1.0" >> $GITHUB_ENV
        #   echo "RELEASE_VERSION=${RELEASE_VERSION#"v"}" >> $GITHUB_ENV
      - name: Print release version
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yawn77/tmplpython:latest
            yawn77/tmplpython:${{ env.RELEASE_VERSION }}
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
